# Astrograph.io Open Source Project
#
# https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md

VERSION="2.1.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://stellarid.io/federation/"
ACCOUNTS=[
  "GDMAU3NHV4H7NZF5PY6O6SULIUKIIHPRYOKM7HMREK4BW65VHMDKNM6M",
  "GDB42WFNRYO66UEMEHIYHAF4I235HG2SIPCC64QLVHSHYH3ZXES7ENQG",
]

[DOCUMENTATION]
ORG_DBA = "Astrograph"
ORG_GITHUB = "astroband"
ORG_KEYBASE = "astrograph"
ORG_LOGO = "https://astrograph.io/logo.svg"
ORG_NAME = "Astrograph Open Source Project"
ORG_OFFICIAL_EMAIL = "team@astrograph.io"
ORG_URL = "https://astrograph.io"

[[PRINCIPALS]]
email = "nebolsin@gmail.com"
name = "Sergey Nebolsin"
github = "nebolsin"
keybase = "nebolsin"
telegram = "nebolsin"
twitter = "nebolsin"
address = "GDB42WFNRYO66UEMEHIYHAF4I235HG2SIPCC64QLVHSHYH3ZXES7ENQG"
alias = "nebolsin"

[[PRINCIPALS]]
email = "gzigzigzeo@gmail.com"
name = "Viktor Sokolov"
github = "gzigzigzeo"
keybase = "gzigzigzeo"
telegram = "gzigzigzeo"
twitter = "gzigzigzeo"

[[PRINCIPALS]]
email = "charlie.vmk@gmail.com"
name = "Timur Ramazanov"
github = "charlie-wasp"
keybase = "charlie_wasp"
telegram = "charlie_wasp"
twitter = "charlie_wasp"

[[VALIDATORS]]
ALIAS = "astrocore-do"
DISPLAY_NAME = "Astrograph (Netherlands)"
PUBLIC_KEY = "GDMAU3NHV4H7NZF5PY6O6SULIUKIIHPRYOKM7HMREK4BW65VHMDKNM6M"
HOST = "do01.astrograph.io"
